steps:
  - label: ":cypress: Run staging tests"
    agents:
      queue: "default"
    command:
      - 'echo "Running staging tests"'
      - "set -e"
      - 'echo "Running staging tests"'
      - "npm install"
      - "EXIT_CODE=0"
      - 'echo \${EXIT_CODE}'
      - npx cypress run --spec 'cypress/e2e/ui.cy.ts'
    artifact_paths:
      - 'cypress/videos/**/*.mp4'
      - 'cypress/screenshots/*'



notify:
  - email: 'kritika.vohra@thoughtworks.com'