steps:
  - label: ":cypress: Run staging tests"
    agents:
      queue: "default"
    # env:
    #   - MODULE=$MODULE
    # plugins: 
      environment:
        - MODULE=$MODULE
    command:
      - 'echo "Running staging tests"'
      - "set -e"
      - "npm install"
      - "MODULE=$${MODULE:-login}"
      - echo $${MODULE}
      - npm run cy:run:$$MODULE'
      - "EXIT_CODE=0"
      - 'echo \${EXIT_CODE}'
    artifact_paths:
      - 'cypress/videos/**/*.mp4'
      - 'cypress/screenshots/*'
notify:
  - email: 'test@xyz.com'